trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: First_Job
        steps:
          - bash: node --version
          - bash: java -version
          - bash: python --version
          - bash: mvn -version
          - bash: ls -R $(Build.ArtifactStagingDirectory)

          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)'
              Contents: |
                **/*.tf
                **/*.yaml
              TargetFolder: '$(Build.ArtifactStagingDirectory)'